/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param eventId 
 * @param activityId 
 * @param eventTitle 
 * @param activityTitle 
 */
@Serializable

data class EventShortDataResponse (

    @SerialName(value = "eventId")
    val eventId: kotlin.Int? = null,

    @SerialName(value = "activityId")
    val activityId: kotlin.Int? = null,

    @SerialName(value = "eventTitle")
    val eventTitle: kotlin.String? = null,

    @SerialName(value = "activityTitle")
    val activityTitle: kotlin.String? = null

)

