/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param filename 
 * @param presignedUrl 
 */
@Serializable

data class FileDataResponse (

    @SerialName(value = "filename")
    val filename: kotlin.String? = null,

    @SerialName(value = "presignedUrl")
    val presignedUrl: kotlin.String? = null

)

