/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model

import org.itmo.itmoevent.network.model.NotificationResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param content 
 * @param totalPages 
 * @param totalElements 
 * @param last 
 * @param first 
 * @param number 
 */
@Serializable

data class NotificationPageResponse (

    @SerialName(value = "content")
    val content: kotlin.collections.List<NotificationResponse>? = null,

    @SerialName(value = "totalPages")
    val totalPages: kotlin.Int? = null,

    @SerialName(value = "totalElements")
    val totalElements: kotlin.Long? = null,

    @SerialName(value = "last")
    val last: kotlin.Boolean? = null,

    @SerialName(value = "first")
    val first: kotlin.Boolean? = null,

    @SerialName(value = "number")
    val number: kotlin.Int? = null

)

