/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enableEmail 
 * @param enablePush 
 */
@Serializable

data class NotificationSettingsRequest (

    @SerialName(value = "enableEmail")
    val enableEmail: kotlin.Boolean,

    @SerialName(value = "enablePush")
    val enablePush: kotlin.Boolean

)

