/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param seen 
 * @param sentTime 
 * @param link 
 */
@Serializable

data class NotificationResponse (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "seen")
    val seen: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "sent_time")
    val sentTime: java.time.LocalDateTime? = null,

    @SerialName(value = "link")
    val link: kotlin.String? = null

)

