/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model

import org.itmo.itmoevent.network.model.UserSystemRoleResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param total 
 * @param items 
 */
@Serializable

data class PaginatedResponseUserSystemRoleResponse (

    @SerialName(value = "total")
    val total: kotlin.Long? = null,

    @SerialName(value = "items")
    val items: kotlin.collections.List<UserSystemRoleResponse>? = null

)

