/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param participantId 
 * @param isVisited 
 */
@Serializable

data class ParticipantPresenceRequest (

    @SerialName(value = "participantId")
    val participantId: kotlin.Int,

    @SerialName(value = "isVisited")
    val isVisited: kotlin.Boolean

)

