/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param address 
 * @param format 
 * @param room 
 * @param description 
 * @param latitude 
 * @param longitude 
 * @param renderInfo 
 */
@Serializable

data class PlaceResponse (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "format")
    val format: PlaceResponse.Format? = null,

    @SerialName(value = "room")
    val room: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "latitude")
    val latitude: kotlin.Float? = null,

    @SerialName(value = "longitude")
    val longitude: kotlin.Float? = null,

    @SerialName(value = "renderInfo")
    val renderInfo: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: ONLINE,OFFLINE,HYBRID
     */
    @Serializable
    enum class Format(val value: kotlin.String) {
        @SerialName(value = "ONLINE") ONLINE("ONLINE"),
        @SerialName(value = "OFFLINE") OFFLINE("OFFLINE"),
        @SerialName(value = "HYBRID") HYBRID("HYBRID");
    }
}

