/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param address 
 * @param format 
 * @param room 
 * @param description 
 * @param latitude 
 * @param longitude 
 */
@Serializable

data class PlaceRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "format")
    val format: PlaceRequest.Format,

    @SerialName(value = "room")
    val room: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "latitude")
    val latitude: kotlin.Float,

    @SerialName(value = "longitude")
    val longitude: kotlin.Float

) {

    /**
     * 
     *
     * Values: ONLINE,OFFLINE,HYBRID
     */
    @Serializable
    enum class Format(val value: kotlin.String) {
        @SerialName(value = "ONLINE") ONLINE("ONLINE"),
        @SerialName(value = "OFFLINE") OFFLINE("OFFLINE"),
        @SerialName(value = "HYBRID") HYBRID("HYBRID");
    }
}

