/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model

import org.itmo.itmoevent.network.model.PrivilegeResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param privileges 
 * @param hasOrganizerRolesResponse 
 */
@Serializable

data class PrivilegeWithHasOrganizerRolesResponse (

    @SerialName(value = "privileges")
    val privileges: kotlin.collections.List<PrivilegeResponse>? = null,

    @SerialName(value = "hasOrganizerRolesResponse")
    val hasOrganizerRolesResponse: kotlin.Boolean? = null

)

