/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model

import org.itmo.itmoevent.network.model.UserInfoResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId 
 * @param name 
 * @param surname 
 * @param userInfo 
 * @param lastLoginDate 
 * @param enablePushNotifications 
 * @param enableEmailNotifications 
 * @param devices 
 */
@Serializable

data class ProfileResponse (

    @SerialName(value = "userId")
    val userId: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "surname")
    val surname: kotlin.String? = null,

    @SerialName(value = "userInfo")
    val userInfo: kotlin.collections.List<UserInfoResponse>? = null,

    @Contextual @SerialName(value = "lastLoginDate")
    val lastLoginDate: java.time.LocalDateTime? = null,

    @SerialName(value = "enablePushNotifications")
    val enablePushNotifications: kotlin.Boolean? = null,

    @SerialName(value = "enableEmailNotifications")
    val enableEmailNotifications: kotlin.Boolean? = null,

    @SerialName(value = "devices")
    val devices: kotlin.collections.List<kotlin.String>? = null

)

