/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param returnUrl 
 * @param email 
 */
@Serializable

data class RecoveryPasswordRequest (

    @SerialName(value = "returnUrl")
    val returnUrl: kotlin.String,

    @SerialName(value = "email")
    val email: kotlin.String

)

