/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param surname 
 * @param login 
 * @param type 
 * @param password 
 * @param confirmPassword 
 */
@Serializable

data class RegistrationUserRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "surname")
    val surname: kotlin.String,

    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "type")
    val type: RegistrationUserRequest.Type,

    @SerialName(value = "password")
    val password: kotlin.String,

    @SerialName(value = "confirmPassword")
    val confirmPassword: kotlin.String

) {

    /**
     * 
     *
     * Values: EMAIL
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "EMAIL") EMAIL("EMAIL");
    }
}

