/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model

import org.itmo.itmoevent.network.model.PrivilegeResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param type 
 * @param privileges 
 * @param isEditable 
 */
@Serializable

data class RoleResponse (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "type")
    val type: RoleResponse.Type? = null,

    @SerialName(value = "privileges")
    val privileges: kotlin.collections.List<PrivilegeResponse>? = null,

    @SerialName(value = "isEditable")
    val isEditable: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: SYSTEM,EVENT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "SYSTEM") SYSTEM("SYSTEM"),
        @SerialName(value = "EVENT") EVENT("EVENT");
    }
}

