/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param description 
 * @param isEvent 
 * @param privileges 
 */
@Serializable

data class RoleRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "isEvent")
    val isEvent: kotlin.Boolean,

    @SerialName(value = "privileges")
    val privileges: kotlin.collections.List<kotlin.Int>

)

