/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model

import org.itmo.itmoevent.network.model.EventShortDataResponse
import org.itmo.itmoevent.network.model.FileDataResponse
import org.itmo.itmoevent.network.model.PlaceShortDataResponse
import org.itmo.itmoevent.network.model.UserShortDataResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param event 
 * @param title 
 * @param description 
 * @param taskStatus 
 * @param assignee 
 * @param place 
 * @param creationTime 
 * @param deadline 
 * @param reminder 
 * @param fileData 
 */
@Serializable

data class TaskResponse (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "event")
    val event: EventShortDataResponse? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "taskStatus")
    val taskStatus: TaskResponse.TaskStatus? = null,

    @SerialName(value = "assignee")
    val assignee: UserShortDataResponse? = null,

    @SerialName(value = "place")
    val place: PlaceShortDataResponse? = null,

    @Contextual @SerialName(value = "creationTime")
    val creationTime: java.time.LocalDateTime? = null,

    @Contextual @SerialName(value = "deadline")
    val deadline: java.time.LocalDateTime? = null,

    @Contextual @SerialName(value = "reminder")
    val reminder: java.time.LocalDateTime? = null,

    @SerialName(value = "fileData")
    val fileData: kotlin.collections.List<FileDataResponse>? = null

) {

    /**
     * 
     *
     * Values: NEW,IN_PROGRESS,EXPIRED,DONE
     */
    @Serializable
    enum class TaskStatus(val value: kotlin.String) {
        @SerialName(value = "NEW") NEW("NEW"),
        @SerialName(value = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @SerialName(value = "EXPIRED") EXPIRED("EXPIRED"),
        @SerialName(value = "DONE") DONE("DONE");
    }
}

