/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param eventId 
 * @param title 
 * @param description 
 * @param deadline 
 * @param reminder 
 * @param assigneeId 
 * @param taskStatus 
 * @param placeId 
 */
@Serializable

data class TaskRequest (

    @SerialName(value = "eventId")
    val eventId: kotlin.Int,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @Contextual @SerialName(value = "deadline")
    val deadline: java.time.LocalDateTime,

    @Contextual @SerialName(value = "reminder")
    val reminder: java.time.LocalDateTime,

    @SerialName(value = "assigneeId")
    val assigneeId: kotlin.Int? = null,

    @SerialName(value = "taskStatus")
    val taskStatus: TaskRequest.TaskStatus? = null,

    @SerialName(value = "placeId")
    val placeId: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: NEW,IN_PROGRESS,EXPIRED,DONE
     */
    @Serializable
    enum class TaskStatus(val value: kotlin.String) {
        @SerialName(value = "NEW") NEW("NEW"),
        @SerialName(value = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @SerialName(value = "EXPIRED") EXPIRED("EXPIRED"),
        @SerialName(value = "DONE") DONE("DONE");
    }
}

