/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.itmo.itmoevent.network.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param surname 
 * @param login 
 * @param type 
 * @param systemRoles 
 * @param eventRoles 
 */
@Serializable

data class UserResponse (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "surname")
    val surname: kotlin.String? = null,

    @SerialName(value = "login")
    val login: kotlin.String? = null,

    @SerialName(value = "type")
    val type: UserResponse.Type? = null,

    @SerialName(value = "systemRoles")
    val systemRoles: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "eventRoles")
    val eventRoles: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null

) {

    /**
     * 
     *
     * Values: EMAIL
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "EMAIL") EMAIL("EMAIL");
    }
}

